### ISSUE TITLE
Counting commands

### ISSUE THREAD

**Issue by TheSecurity** [discord-bot-tutorial/Community-Discord-BOT#105]
Miunie already has got 4 commands that are able to do basic mathematical operations.
I think it would be nice to put it all together. And maybe add some basic equations as well.

**Describe the solution you'd like**
Merge these commands into a single Math one.

**Describe alternatives you've considered**
Alternative would be to just get rid of this feature. :smile:

**Comment by petrspelos** [comment]
We could perhaps even use some sort of a Math API. :slightly_smiling_face:
