### ISSUE TITLE
[Refactor] Convert global accounts into services

### ISSUE THREAD

**Issue by Charly6596** [discord-bot-tutorial/Community-Discord-BOT#112]
**Is your feature request related to a problem? Please describe.**
There are many benefits using DI over static classes, for example, if we use DI, would be easier to mock and test any code that requires a GlobalUserAccount or GlobalGuildAccount as dependency.

**Describe the solution you'd like**
Refactor `GlobalUserAccounts` and `GlobalGuildAccounts`, both classes got similar methods, like the `SaveAccounts`, would be nice to create a class, GlobalAccount, with methods in common, such as create, get, and save. Also, use Dependency Injection instead of static classes. 
This issue is similar to #69

**Comment by petrspelos** [comment]
I'll go for this one. 👍
