### ISSUE TITLE
Token not configured right?

### ISSUE THREAD

**Issue by AkaFarukon** [discord-bot-tutorial/Community-Discord-BOT#118]
So I have forked and cloned this project, followed all the steps but when I compile, I keep getting
``An exception occurred. Your token might not be configured, or it might be wrong.``

I just have no idea on how to fix this or correct it??

**Comment by petrspelos** [comment]
It means the config file got generated, but you haven't fill your token, yet.

If you are not using the arguments to pass in your token, then in your build directory, search for a file called `config.json` in a `resrouces` directory.

In it, you can define your bot token manually. :slightly_smiling_face: 

:information_source: Note that this token can be overwritten by potential launch arguments.

**Comment by AkaFarukon** [comment]
Ah, alright, let me give it a go.

**Comment by AkaFarukon** [comment]
> It means the config file got generated, but you haven't fill your token, yet.
> 
> If you are not using the arguments to pass in your token, then in your build directory, search for a file called `config.json` in a `resrouces` directory.
> 
> In it, you can define your bot token manually. 🙂
> 
> ℹ️ Note that this token can be overwritten by potential launch arguments.

Ok, simple fix, just had to impute token manually. Thank you for your time!
