### ISSUE TITLE
Add more information to FIRST-CONTRIBUTION.md

### ISSUE THREAD

**Issue by petrspelos** [discord-bot-tutorial/Community-Discord-BOT#120]
The current [FIRST-CONTRIBUTION.md](https://github.com/discord-bot-tutorial/Community-Discord-BOT/blob/master/FIRST-CONTRIBUTION.md) assumes some knowledge about the Git CLI.

**Describe the solution you'd like**
It would be nice if we could get more beginner friendly approach and perhaps describe the process of getting Git.

* Optionally, we could perhaps describe the process for doing it using Github Desktop.
* We could also link to the Community Discord Bot contribution video on my Channel.
* We could add some screenshots of the process, especially for GitHub for Desktop.
* Perhaps linking to download pages of Git, GitHub Desktop, etc. would be useful.

:information_source: If you would like to work on this issue, please say so in the comments. We do that so that more people don't accidentally work on the same issue. :blush:

**Comment by LeMorrow** [comment]
I'll try to work on this :)
