### ISSUE TITLE
HTML/CSS design of the github pages main page

### ISSUE THREAD

**Issue by petrspelos** [discord-bot-tutorial/Community-Discord-BOT#132]
**Describe the solution you'd like**
Our current GitHub page for Miunie (you can find that in the `Pages` folder in the root of this repo) is quite bare and it would be cool if we could somehow extend it and make it look a bit more modern.

**What can I change?**
Feel free to include design frameworks such as Bootstrap, Materialize, etc.
Just make sure it is simple enough for manual editting, so let's not go through the CMS, Angular, Vue.js route. :slightly_smiling_face: Unless you of course provide a pretty good argument for it.

**Additional context**
Please feel free to open more issues relevant to the page. :two_hearts: 

*********
:information_source: if you would like to work on this issue, say so in the comments. We do this to make sure two people don't accidentally work on the same problem. :blush:

**Comment by sebastiaanspeck** [comment]
Love to do this!

**Comment by sebastiaanspeck** [comment]
The avatar-link is broken. Got a new one?

**Comment by petrspelos** [comment]
@sebastiaanspeck yep, here's one:
<https://i.imgur.com/v1eHLkD.png>

**Comment by Cre8tiveKel** [comment]
Are you still needing people to work on this?

**Comment by petrspelos** [comment]
@Cre8tiveKel you might want to check out #148. :slightly_smiling_face:
