### ISSUE TITLE
Invalid invite to discord server

### ISSUE THREAD

**Issue by HD97300** [discord-bot-tutorial/Community-Discord-BOT#145]
**Describe the bug**
There are two broken links to discord server on [CONTRIBUTING page](https://github.com/discord-bot-tutorial/Community-Discord-BOT/blob/master/CONTRIBUTING.md)

**To Reproduce**
1. Go to CONTRIBUTING page
2. Click on any **Discord Server** link
3. See error

**Expected behavior**
Invite link never expire.

**Screenshots**
![expired_invite](https://user-images.githubusercontent.com/13046608/47132761-51019200-d2ae-11e8-89c3-ae1611d8d9f2.png)

**Comment by HD97300** [comment]
@petrspelos, about labels for this issue. I'm not sure that someone completely new in this project can add a link to your discord server. To generate it you need to be a member already, so..

**Comment by petrspelos** [comment]
@HD97300 A link to the discord server is under every part of the tutorial series on my YouTube.
