### ISSUE TITLE
[HTML/CSS] The footer doesn't stick to bottom

### ISSUE THREAD

**Issue by petrspelos** [discord-bot-tutorial/Community-Discord-BOT#148]
**Describe the bug**
In our Miunie home page, the footer doesn't stick to the bottom of the window.

**To Reproduce**
1. Go to 'https://discord-bot-tutorial.github.io/Community-Discord-BOT/Pages/'
2. Scroll down
3. The footer doesn't follow

**Screenshots**
![Screen](https://i.imgur.com/1PeyCw2.png)

**Additional Context**
One more tiny issue is that the page says "All rights reserved" instead of an MIT license.

**Comment by GelaniNijraj** [comment]
Looking into this.
