### ISSUE TITLE
Help command exception

### ISSUE THREAD

**Issue by petrspelos** [discord-bot-tutorial/Community-Discord-BOT#81]
The help command is not checking for the size of the embed.

When the size reaches 6000 characters an exception is thrown and no help is sent.

* Create a mechanism for either preventing the issue, or resolving it in some other way. 

_Suggestion:_
_One way of doing this is separating the help output into multiple messages. Or providing an external link._

**Comment by Raunow** [comment]
How I went about solving the problem was to introduce "Pages" 
You would write a number after the command to tell the bot which page to show. 
It would then fetch the relevant info and format it to fit in the embed.

**Comment by petrspelos** [comment]
I think @ZottelvonUrvieh already did some pagination for the Trivia game.

Maybe that can be reused? :thinking:
