### ISSUE TITLE
Expanded Context

### ISSUE THREAD

**Issue by petrspelos** [discord-bot-tutorial/Community-Discord-BOT#94]
In order to provide more features and richer experience, a Command Context expansion could be created.

## What would the expansion hold?
* **GlobalUseraccount of called (if it exists)**
* **Command history** (Last 3-5 command used by this user)

## About the Command history
To make this work easily, I think this should be automatically intercepted after each command execution.
This means the execution result should be standardized.

## What kind of features would this enable?
Context present features. For example:
```
User: @Miunie daily

Miunie: You can get the next daily in 2 h 5 m.

[Some time passes]

User: @Miunie how long?

Miunie: You still need to wait 5 minutes to use "daily".

User2: @Miunie how long?

Miunie: I'm not sure what you're talking about, try to use the command you're referring to.
```
**********
:information_source: This feature is of course, very experimental and might not be implemented. But I'm interested in your opinion, so feel free to comment down bellow.

**Comment by Charly6596** [comment]
I'd add the *Command history* information to the GlobalUseraccount instead of the context, and I will give it a try!
